POST http://localhost:3001/videos
Content-Type: application/json

{
  "title": "Video node",
  "description": "Descrição do video 01",
  "duration": 180
}

###

GET http://localhost:3001/videos

###

PUT http://localhost:3001/videos/2159c879-10a7-4cfb-bbd8-6333f1916b1f
Content-Type: application/json

{
  "title": "Video 02",
  "description": "Descrição do video 01",
  "duration": 180
}

###

DELETE http://localhost:3001/videos/ea1dec35-c744-478b-8927-3d1ed89d1e17